/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutImage {
  'imageType' : string,
  'imageUrl' : string,
  'imageBase64' : string,
}
export interface Clinic {
  'name' : string,
  'description' : string,
  'address' : string,
  'mapUrl' : string,
  'phone' : string,
  'bookingUrl' : string,
}
export interface ClinicInput {
  'name' : string,
  'description' : string,
  'address' : string,
  'mapUrl' : string,
  'phone' : string,
  'bookingUrl' : string,
}
export interface GlowEffectSetting {
  'color' : string,
  'enabled' : boolean,
  'style' : string,
  'intensity' : bigint,
}
export interface HeroSettings {
  'showConnectionLines' : boolean,
  'backgroundEffect' : string,
  'footerGlowEffect' : GlowEffectSetting,
  'particleColor' : string,
  'particleCount' : bigint,
  'heroGradientStart' : string,
  'particleSpeed' : number,
  'heroGradientEnd' : string,
  'mouseInteraction' : boolean,
  'heroGlowEffect' : GlowEffectSetting,
  'particleSize' : number,
  'glassmorphismEnabled' : boolean,
}
export interface Images {
  'heroBackgroundUrl' : string,
  'heroBackgroundBase64' : string,
}
export interface Service {
  'title' : string,
  'description' : string,
  'iconBase64' : string,
  'iconUrl' : string,
}
export interface ServiceInput {
  'title' : string,
  'description' : string,
  'iconBase64' : string,
  'iconUrl' : string,
}
export interface SocialLink { 'url' : string, 'platform' : string }
export interface SocialLinkInput { 'url' : string, 'platform' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClinic' : ActorMethod<[ClinicInput, string], undefined>,
  'addService' : ActorMethod<[ServiceInput, string], undefined>,
  'addSocialLink' : ActorMethod<[SocialLinkInput, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAboutImage' : ActorMethod<[string], undefined>,
  'deleteClinic' : ActorMethod<[bigint, string], undefined>,
  'deleteHeaderImage' : ActorMethod<[string], undefined>,
  'deleteHeroBackgroundImage' : ActorMethod<[string], undefined>,
  'deleteService' : ActorMethod<[bigint, string], undefined>,
  'deleteServiceIcon' : ActorMethod<[bigint, string], undefined>,
  'deleteSocialLink' : ActorMethod<[bigint, string], undefined>,
  'getAboutSection' : ActorMethod<[], [string, AboutImage]>,
  'getAllClinics' : ActorMethod<[], Array<[bigint, Clinic]>>,
  'getAllContent' : ActorMethod<
    [],
    {
      'clinics' : Array<[bigint, Clinic]>,
      'headerImageUrl' : string,
      'heroSettings' : HeroSettings,
      'siteTitle' : string,
      'aboutImage' : AboutImage,
      'aboutSection' : string,
      'socialLinks' : Array<[bigint, SocialLink]>,
      'headerImageBase64' : string,
      'services' : Array<[bigint, Service]>,
      'footerContent' : string,
      'images' : Images,
    }
  >,
  'getAllServices' : ActorMethod<[], Array<[bigint, Service]>>,
  'getAllSocialLinks' : ActorMethod<[], Array<[bigint, SocialLink]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFooterContent' : ActorMethod<[], string>,
  'getHeaderImageBase64' : ActorMethod<[], string>,
  'getHeroSettings' : ActorMethod<[], HeroSettings>,
  'getImages' : ActorMethod<[], Images>,
  'getServiceIconBase64' : ActorMethod<[bigint], string>,
  'getSiteTitle' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Login with username/password; returns a session token on success.
   */
  'login' : ActorMethod<[string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAboutImage' : ActorMethod<[AboutImage, string], undefined>,
  'updateAboutSection' : ActorMethod<[string, string], undefined>,
  'updateClinic' : ActorMethod<[bigint, ClinicInput, string], undefined>,
  'updateFooterContent' : ActorMethod<[string, string], undefined>,
  'updateHeaderImageBase64' : ActorMethod<[string, string], undefined>,
  'updateHeroBackgroundImage' : ActorMethod<
    [string, string, string],
    undefined
  >,
  'updateHeroSettings' : ActorMethod<[HeroSettings, string], undefined>,
  'updateService' : ActorMethod<[bigint, ServiceInput, string], undefined>,
  'updateServiceIconBase64' : ActorMethod<[bigint, string, string], undefined>,
  'updateSiteTitle' : ActorMethod<[string, string], undefined>,
  'updateSocialLink' : ActorMethod<
    [bigint, SocialLinkInput, string],
    undefined
  >,
  'upgradePersistentContent' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      Array<[bigint, ClinicInput]>,
      Array<[bigint, ServiceInput]>,
      string,
    ],
    undefined
  >,
  /**
   * / Validates a session token (public, read-only check).
   */
  'validateSessionToken' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];