/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ClinicInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'address' : IDL.Text,
  'mapUrl' : IDL.Text,
  'phone' : IDL.Text,
  'bookingUrl' : IDL.Text,
});
export const ServiceInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'iconBase64' : IDL.Text,
  'iconUrl' : IDL.Text,
});
export const SocialLinkInput = IDL.Record({
  'url' : IDL.Text,
  'platform' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Clinic = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'address' : IDL.Text,
  'mapUrl' : IDL.Text,
  'phone' : IDL.Text,
  'bookingUrl' : IDL.Text,
});
export const IdleHeroSettings = IDL.Record({
  'heroHeight' : IDL.Variant({ 'normal' : IDL.Null }),
  'glassmorphismIntensity' : IDL.Float64,
  'backgroundBlur' : IDL.Bool,
  'particlePreset' : IDL.Text,
  'particleMaxSize' : IDL.Float64,
  'particleOpacity' : IDL.Float64,
  'bgGradientStart' : IDL.Text,
  'particleColor' : IDL.Text,
  'particleCount' : IDL.Nat,
  'mouseParallaxEnabled' : IDL.Bool,
  'animationSpeed' : IDL.Float64,
  'particleSpeed' : IDL.Float64,
  'particleMinSize' : IDL.Float64,
  'overlayOpacity' : IDL.Float64,
  '_version' : IDL.Nat,
  'bgGradientEnd' : IDL.Text,
  'textColor' : IDL.Text,
});
export const SocialLink = IDL.Record({
  'url' : IDL.Text,
  'platform' : IDL.Text,
});
export const Service = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'iconBase64' : IDL.Text,
  'iconUrl' : IDL.Text,
});
export const Images = IDL.Record({
  'heroBackgroundUrl' : IDL.Text,
  'heroBackgroundBase64' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClinic' : IDL.Func([ClinicInput, IDL.Text], [], []),
  'addService' : IDL.Func([ServiceInput, IDL.Text], [], []),
  'addSocialLink' : IDL.Func([SocialLinkInput, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAboutImage' : IDL.Func([IDL.Text], [], []),
  'deleteClinic' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'deleteHeaderImage' : IDL.Func([IDL.Text], [], []),
  'deleteHeroBackgroundImage' : IDL.Func([IDL.Text], [], []),
  'deleteService' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'deleteServiceIcon' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'deleteSocialLink' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAboutImageBase64' : IDL.Func([], [IDL.Text], ['query']),
  'getAboutSection' : IDL.Func([], [IDL.Text, IDL.Text], ['query']),
  'getAllClinics' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Clinic))],
      ['query'],
    ),
  'getAllContent' : IDL.Func(
      [],
      [
        IDL.Record({
          'clinics' : IDL.Vec(IDL.Tuple(IDL.Nat, Clinic)),
          'headerImageUrl' : IDL.Text,
          'heroSettings' : IdleHeroSettings,
          'siteTitle' : IDL.Text,
          'aboutImageBase64' : IDL.Text,
          'aboutSection' : IDL.Text,
          'socialLinks' : IDL.Vec(IDL.Tuple(IDL.Nat, SocialLink)),
          'aboutImageUrl' : IDL.Text,
          'headerImageBase64' : IDL.Text,
          'services' : IDL.Vec(IDL.Tuple(IDL.Nat, Service)),
          'footerContent' : IDL.Text,
          'images' : Images,
        }),
      ],
      ['query'],
    ),
  'getAllServices' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Service))],
      ['query'],
    ),
  'getAllSocialLinks' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, SocialLink))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(IDL.Record({ 'name' : IDL.Text }))],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFooterContent' : IDL.Func([], [IDL.Text], ['query']),
  'getHeaderImageBase64' : IDL.Func([], [IDL.Text], ['query']),
  'getHeroSettings' : IDL.Func([], [IdleHeroSettings], ['query']),
  'getImages' : IDL.Func([], [Images], ['query']),
  'getServiceIconBase64' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getSiteTitle' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Record({ 'name' : IDL.Text }))],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Record({ 'name' : IDL.Text })],
      [],
      [],
    ),
  'updateAboutImageBase64' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateAboutSection' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateClinic' : IDL.Func([IDL.Nat, ClinicInput, IDL.Text], [], []),
  'updateFooterContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateHeaderImageBase64' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateHeroBackgroundImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateHeroSettings' : IDL.Func([IdleHeroSettings, IDL.Text], [], []),
  'updateService' : IDL.Func([IDL.Nat, ServiceInput, IDL.Text], [], []),
  'updateServiceIconBase64' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateSiteTitle' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateSocialLink' : IDL.Func([IDL.Nat, SocialLinkInput, IDL.Text], [], []),
  'upgradePersistentContent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Tuple(IDL.Nat, ClinicInput)),
        IDL.Vec(IDL.Tuple(IDL.Nat, ServiceInput)),
        IDL.Text,
      ],
      [],
      [],
    ),
  'validateSessionToken' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ClinicInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'address' : IDL.Text,
    'mapUrl' : IDL.Text,
    'phone' : IDL.Text,
    'bookingUrl' : IDL.Text,
  });
  const ServiceInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'iconBase64' : IDL.Text,
    'iconUrl' : IDL.Text,
  });
  const SocialLinkInput = IDL.Record({
    'url' : IDL.Text,
    'platform' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Clinic = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'address' : IDL.Text,
    'mapUrl' : IDL.Text,
    'phone' : IDL.Text,
    'bookingUrl' : IDL.Text,
  });
  const IdleHeroSettings = IDL.Record({
    'heroHeight' : IDL.Variant({ 'normal' : IDL.Null }),
    'glassmorphismIntensity' : IDL.Float64,
    'backgroundBlur' : IDL.Bool,
    'particlePreset' : IDL.Text,
    'particleMaxSize' : IDL.Float64,
    'particleOpacity' : IDL.Float64,
    'bgGradientStart' : IDL.Text,
    'particleColor' : IDL.Text,
    'particleCount' : IDL.Nat,
    'mouseParallaxEnabled' : IDL.Bool,
    'animationSpeed' : IDL.Float64,
    'particleSpeed' : IDL.Float64,
    'particleMinSize' : IDL.Float64,
    'overlayOpacity' : IDL.Float64,
    '_version' : IDL.Nat,
    'bgGradientEnd' : IDL.Text,
    'textColor' : IDL.Text,
  });
  const SocialLink = IDL.Record({ 'url' : IDL.Text, 'platform' : IDL.Text });
  const Service = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'iconBase64' : IDL.Text,
    'iconUrl' : IDL.Text,
  });
  const Images = IDL.Record({
    'heroBackgroundUrl' : IDL.Text,
    'heroBackgroundBase64' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClinic' : IDL.Func([ClinicInput, IDL.Text], [], []),
    'addService' : IDL.Func([ServiceInput, IDL.Text], [], []),
    'addSocialLink' : IDL.Func([SocialLinkInput, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAboutImage' : IDL.Func([IDL.Text], [], []),
    'deleteClinic' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'deleteHeaderImage' : IDL.Func([IDL.Text], [], []),
    'deleteHeroBackgroundImage' : IDL.Func([IDL.Text], [], []),
    'deleteService' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'deleteServiceIcon' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'deleteSocialLink' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAboutImageBase64' : IDL.Func([], [IDL.Text], ['query']),
    'getAboutSection' : IDL.Func([], [IDL.Text, IDL.Text], ['query']),
    'getAllClinics' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Clinic))],
        ['query'],
      ),
    'getAllContent' : IDL.Func(
        [],
        [
          IDL.Record({
            'clinics' : IDL.Vec(IDL.Tuple(IDL.Nat, Clinic)),
            'headerImageUrl' : IDL.Text,
            'heroSettings' : IdleHeroSettings,
            'siteTitle' : IDL.Text,
            'aboutImageBase64' : IDL.Text,
            'aboutSection' : IDL.Text,
            'socialLinks' : IDL.Vec(IDL.Tuple(IDL.Nat, SocialLink)),
            'aboutImageUrl' : IDL.Text,
            'headerImageBase64' : IDL.Text,
            'services' : IDL.Vec(IDL.Tuple(IDL.Nat, Service)),
            'footerContent' : IDL.Text,
            'images' : Images,
          }),
        ],
        ['query'],
      ),
    'getAllServices' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Service))],
        ['query'],
      ),
    'getAllSocialLinks' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, SocialLink))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(IDL.Record({ 'name' : IDL.Text }))],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFooterContent' : IDL.Func([], [IDL.Text], ['query']),
    'getHeaderImageBase64' : IDL.Func([], [IDL.Text], ['query']),
    'getHeroSettings' : IDL.Func([], [IdleHeroSettings], ['query']),
    'getImages' : IDL.Func([], [Images], ['query']),
    'getServiceIconBase64' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getSiteTitle' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Record({ 'name' : IDL.Text }))],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Record({ 'name' : IDL.Text })],
        [],
        [],
      ),
    'updateAboutImageBase64' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateAboutSection' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateClinic' : IDL.Func([IDL.Nat, ClinicInput, IDL.Text], [], []),
    'updateFooterContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateHeaderImageBase64' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateHeroBackgroundImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateHeroSettings' : IDL.Func([IdleHeroSettings, IDL.Text], [], []),
    'updateService' : IDL.Func([IDL.Nat, ServiceInput, IDL.Text], [], []),
    'updateServiceIconBase64' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateSiteTitle' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateSocialLink' : IDL.Func([IDL.Nat, SocialLinkInput, IDL.Text], [], []),
    'upgradePersistentContent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Tuple(IDL.Nat, ClinicInput)),
          IDL.Vec(IDL.Tuple(IDL.Nat, ServiceInput)),
          IDL.Text,
        ],
        [],
        [],
      ),
    'validateSessionToken' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };